document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="extra.css?v=2026081311">');
const A=document.querySelector('#app'),T=document.querySelector('#toast');let view='list',filter='all',stage=0,period='long',uploaded=false,selectedCreateType='',advancedOpen=false;
let returnStage=null,planSnapshot=null,groupSnapshot=null;
const d=new Date(),today=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,compact=today.replaceAll('-','');
const plan={name:`RTB计划｜${compact}｜001`,budget:'',start:today,end:''},group={name:'',geo:'',inv:'',fmt:'',bill:'',bid:'',device:'全部设备',os:'全部系统',schedule:'全天'},creative={name:'',landing:'',headline:''};
const rows=[['XX汽车｜新车上市｜App首页开屏｜0812-0818｜01','C-50271','cpd','2026-08-12 至 2026-08-18','投放中','代投运营：Amy','124万','8,420'],['优选商城｜欧洲再营销｜信息流｜长期｜01','C-50301','rtb','长期投放','投放中','每日预算：$120','68万','5,440'],['星游科技｜暑期拉新｜游戏中心激励视频｜0810-0824｜01','C-50288','cpd','2026-08-10 至 2026-08-24','投放中','代投运营：Ken','420万','24,500'],['未来金融｜巴西获客｜H5插屏｜长期｜01','C-50322','rtb','长期投放','待添加创意','每日预算：$100','—','—']];
function toast(s){T.textContent=s;T.classList.add('show');setTimeout(()=>T.classList.remove('show'),1600)}function val(id){return document.querySelector('#'+id)?.value.trim()||''}
function list(){view='list';render()}function start(){view='create';stage=0;period='long';uploaded=false;advancedOpen=false;plan.name=`RTB计划｜${compact}｜001`;plan.budget='';plan.start=today;plan.end='';Object.assign(group,{name:'',geo:'',inv:'',fmt:'',bill:'',bid:'',device:'全部设备',os:'全部系统',schedule:'全天'});Object.assign(creative,{name:'',landing:'',headline:''});render()}
function listHTML(){let rs=rows.filter(r=>filter==='all'||r[2]===filter);return `<div class="top"><div><h1>广告投放</h1><p>统一查看 CPD 代投与 RTB 自助投放计划</p></div><button class="primary" onclick="openCreateChoice()">＋ 新建投放</button></div><div class="toolbar"><div class="seg"><button class="${filter==='all'?'on':''}" onclick="filter='all';render()">全部投放</button><button class="${filter==='cpd'?'on':''}" onclick="filter='cpd';render()">CPD</button><button class="${filter==='rtb'?'on':''}" onclick="filter='rtb';render()">RTB</button></div><input placeholder="搜索计划名称 / ID"><span></span><small>CPD 由运营代投；RTB 由广告主自助管理</small></div><div class="card table-wrap"><table class="table"><thead><tr><th>广告计划</th><th>投放类型</th><th>投放周期</th><th>状态</th><th>预算 / 代投运营</th><th>展示</th><th>点击</th><th>操作</th></tr></thead><tbody>${rs.map(r=>`<tr><td><b>${r[0]}</b><small>${r[1]}</small></td><td><span class="type ${r[2]}">${r[2]==='cpd'?'CPD 代投':'RTB 自助投放'}</span></td><td>${r[3]}</td><td><span class="status ${r[4].includes('待')?'wait':''}">${r[4]}</span></td><td>${r[5]}</td><td>${r[6]}</td><td>${r[7]}</td><td class="row-actions"><button onclick="toast('查看计划详情（演示）')">查看</button>${r[2]==='rtb'?'<button onclick="toast(\'管理 RTB 计划（演示）\')">管理</button>':''}</td></tr>`).join('')}</tbody></table></div>`}
function openCreateChoice(){selectedCreateType='';document.body.insertAdjacentHTML('beforeend',`<div class="choice-mask" id="choiceMask" onclick="closeCreateChoice(event)"><div class="choice-modal" role="dialog" aria-modal="true" aria-labelledby="choiceTitle" onclick="event.stopPropagation()"><div class="choice-head"><div><h2 id="choiceTitle">新建投放</h2><p>选择投放方式，再点击继续</p></div><button aria-label="关闭" onclick="closeCreateChoice()">×</button></div><div class="choice-grid"><button class="choice-card" data-type="rtb" aria-pressed="false" onclick="selectCreateType('rtb')"><span class="choice-check">✓</span><em>可自助创建</em><small>RTB</small><b>自主竞价投放</b><p>自主设置预算、出价、定向、库存和广告创意。</p></button><button class="choice-card" data-type="cpd" aria-pressed="false" onclick="selectCreateType('cpd')"><span class="choice-check">✓</span><em>由运营协助</em><small>CPD</small><b>运营代投</b><p>价格、库存和排期由销售及广告运营确认。</p></button></div><div class="choice-actions"><span class="choice-help" id="choiceHelp">请选择一种投放方式</span><button class="outline" onclick="closeCreateChoice()">取消</button><button class="primary" id="createContinue" disabled onclick="confirmCreateType()">继续</button></div></div></div>`);requestAnimationFrame(()=>document.querySelector('#choiceMask')?.classList.add('visible'))}
function selectCreateType(type){selectedCreateType=type;document.querySelectorAll('.choice-card').forEach(card=>{const picked=card.dataset.type===type;card.classList.toggle('selected',picked);card.setAttribute('aria-pressed',picked)});const btn=document.querySelector('#createContinue'),help=document.querySelector('#choiceHelp');if(btn){btn.disabled=false;btn.classList.remove('ready');requestAnimationFrame(()=>btn.classList.add('ready'))}if(help)help.textContent=type==='rtb'?'已选择 RTB 自主竞价投放':'已选择 CPD 运营代投'}
function confirmCreateType(){if(!selectedCreateType)return;if(selectedCreateType==='cpd'){toast('CPD 暂不开放自助创建，请联系销售团队下单');return}closeCreateChoice();start()}
function closeCreateChoice(e){if(e&&e.target.id!=='choiceMask')return;const mask=document.querySelector('#choiceMask');if(!mask)return;mask.classList.remove('visible');setTimeout(()=>mask.remove(),180)}
function exit(){if(stage===0&&returnStage===null&&!confirm('广告计划尚未创建，返回后当前填写内容不会保留。确定返回吗？'))return;if(returnStage!==null&&!confirm(`对${stage===0?'广告计划':'广告组'}的修改尚未保存，确定返回广告投放列表吗？`))return;returnStage=null;planSnapshot=null;groupSnapshot=null;list()}
function invalid(id,message){const el=document.querySelector('#'+id);if(el){el.classList.add('invalid');el.focus()}toast(message);return false}
function keepPlan(){plan.name=val('pname');plan.budget=val('budget');plan.start=val('start');plan.end=val('end');if(!plan.name)return invalid('pname','请输入计划名称');if(!plan.budget)return invalid('budget','请输入预算');if(+plan.budget<100)return invalid('budget','预算不能低于 100 USD');if(!plan.start)return invalid('start','请选择开始日期');if(period==='fixed'&&!plan.end)return invalid('end','请选择结束日期');if(period==='fixed'&&plan.end<plan.start)return invalid('end','结束日期不能早于开始日期');return true}
function captureGroup(){if(stage!==1)return;Object.assign(group,{name:val('gname'),geo:val('geo'),inv:val('inv'),fmt:val('fmt'),bill:val('bill'),bid:val('bid'),device:val('device')||group.device,os:val('os')||group.os,schedule:val('schedule')||group.schedule})}
function captureCreative(){if(stage!==2)return;creative.name=val('cname');creative.landing=val('landing');creative.headline=val('headline')}
function editCompleted(target){if(stage<1)return;if(target===0){captureGroup();captureCreative();planSnapshot={...plan,period};returnStage=stage;stage=0;renderCreate(true);return}if(target===1&&stage===2){captureCreative();groupSnapshot={...group};returnStage=stage;stage=1;renderCreate(true)}}
function cancelPlanEdit(){if(!planSnapshot)return;Object.assign(plan,planSnapshot);period=planSnapshot.period;stage=returnStage;returnStage=null;planSnapshot=null;renderCreate(true)}
function savePlanEdit(){if(!keepPlan())return;if(activePlanRow){activePlanRow[0]=plan.name;activePlanRow[3]=period==='long'?'长期投放':`${plan.start} 至 ${plan.end}`;activePlanRow[5]=period==='long'?`每日预算：$${plan.budget}`:`总预算：$${plan.budget}`}const target=returnStage;returnStage=null;planSnapshot=null;stage=target;toast('广告计划修改已保存');renderCreate(true)}
function cancelGroupEdit(){if(!groupSnapshot)return;Object.assign(group,groupSnapshot);stage=returnStage;returnStage=null;groupSnapshot=null;renderCreate(true)}
function saveGroupEdit(){if(!keepGroup())return;const target=returnStage;returnStage=null;groupSnapshot=null;stage=target;toast('广告组修改已保存');renderCreate(true)}
function planOnly(){if(!keepPlan())return;rows.unshift([plan.name,'C-NEW01','rtb',period==='long'?'长期投放':`${plan.start} 至 ${plan.end}`,'待添加广告组',period==='long'?`每日预算：$${plan.budget}`:`总预算：$${plan.budget}`,'—','—']);toast('广告计划已创建');setTimeout(list,450)}function planNext(){if(!keepPlan())return;transitionToStage(1)}
function keepGroup(){captureGroup();for(const [id,message] of [['gname','请输入广告组名称'],['geo','请选择投放地区'],['inv','请选择流量范围'],['fmt','请选择广告形式'],['bill','请选择计费方式'],['bid','请输入出价']])if(!val(id))return invalid(id,message);if(+group.bid<=0)return invalid('bid','出价必须大于 0 USD');return true}function groupOnly(){if(!keepGroup())return;toast('广告组已创建');setTimeout(list,450)}function groupNext(){if(!keepGroup())return;transitionToStage(2)}
function transitionToStage(next){const editor=document.querySelector('#editor');if(editor){editor.classList.add('leaving');setTimeout(()=>{stage=next;renderCreate(true)},180)}else{stage=next;renderCreate(true)}}
function submitCreative(){captureCreative();if(!creative.name)return invalid('cname','请输入创意名称');if(!creative.landing)return invalid('landing','请输入落地页链接');if(!/^https?:\/\/\S+$/i.test(creative.landing))return invalid('landing','请输入以 http:// 或 https:// 开头的有效链接');if(!uploaded){toast('请选择广告素材');return}if(activePlanRow)activePlanRow[4]='创意审核中';stage=3;renderCreate(true)}
function setPeriod(p){plan.name=val('pname')||plan.name;plan.budget=val('budget');plan.start=val('start')||today;plan.end=val('end');period=p;renderCreate(false)}function suggest(){document.querySelector('#gname').value=`${val('geo')||'地区'}｜${val('inv')||'流量'}｜${val('fmt')||'广告形式'}｜01`}function upload(){creative.name=val('cname')||'summer-feed-1200x628｜01';creative.landing=val('landing');uploaded=true;renderCreate(false)}
function strip(){let x=[];if(stage>0)x.push(`<div class="created-chip"><i>✓</i><div><small>广告计划</small><b>${plan.name}</b></div></div>`);if(stage>1)x.push(`<div class="created-chip"><i>✓</i><div><small>广告组</small><b>${group.name}</b></div></div>`);return x.length?`<div class="created-strip">${x.join(' › ')}</div>`:''}
function planForm(){const editing=returnStage!==null,returnLabel=returnStage===2?'广告创意':'广告组';return `<div class="body"><div class="grid"><div><label>计划名称 <i class="req">*</i></label><input id="pname" value="${plan.name}"><div class="hint">按“投放类型｜创建日期｜当日序号”生成，可修改</div></div><div><label>投放周期 <i class="req">*</i></label><div class="seg"><button class="${period==='long'?'on':''}" onclick="setPeriod('long')">长期投放</button><button class="${period==='fixed'?'on':''}" onclick="setPeriod('fixed')">固定周期</button></div></div><div><label>${period==='long'?'每日预算':'活动总预算'}（USD）<i class="req">*</i></label><input id="budget" type="number" min="100" value="${plan.budget}" placeholder="请输入，不低于 100 USD"><div class="hint">最低预算 100 USD</div></div><div><label>开始日期 <i class="req">*</i></label><input id="start" type="date" value="${plan.start}"><div class="hint">默认从今天开始，可调整</div></div>${period==='fixed'?`<div><label>结束日期 <i class="req">*</i></label><input id="end" type="date" value="${plan.end}"></div>`:''}</div></div><div class="actions"><small>${editing?`保存后返回${returnLabel}，下层已填写内容不会丢失`:'创建后生成正式计划，不保存未提交表单'}</small><div class="save-actions">${editing?`<button class="secondary" onclick="cancelPlanEdit()">取消修改</button><button class="primary" onclick="savePlanEdit()">保存并返回${returnLabel}</button>`:'<button class="secondary" onclick="planOnly()">仅创建计划</button><button class="primary" onclick="planNext()">创建并添加广告组</button>'}</div></div>`}
function groupForm(){const editing=returnStage===2;return `<div class="body"><div class="grid"><div><label>广告组名称 *</label><input id="gname" value="${group.name}" placeholder="填写配置后可使用建议名称"></div><div><label>投放地区 *</label><select id="geo"><option value="">请选择</option><option>德国、法国</option><option>美国</option><option>全球</option></select></div><div><label>流量范围 *</label><select id="inv"><option value="">请选择</option><option>App</option><option>H5 移动网页</option><option>Web 桌面网页</option><option>App + H5</option></select></div><div><label>广告形式 *</label><select id="fmt"><option value="">请选择</option><option>图片信息流</option><option>横幅广告</option><option>开屏图片</option></select></div><div><label>计费方式 *</label><select id="bill"><option value="">请选择</option><option>CPM · 按千次展示</option><option>CPC · 按点击</option></select></div><div><label>出价（USD）*</label><input id="bid" type="number" min="0.01" step="0.01" placeholder="请输入出价"><div class="hint">选择地区和计费方式后展示建议区间</div></div></div><div class="advanced-box"><button class="ghost advanced-toggle" aria-expanded="${advancedOpen}" onclick="toggleAdvanced()">更多定向设置 <span>${advancedOpen?'⌃':'⌄'}</span></button>${advancedOpen?`<div class="advanced-grid"><div><label>设备</label><select id="device"><option>全部设备</option><option>手机</option><option>平板</option></select></div><div><label>操作系统</label><select id="os"><option>全部系统</option><option>Android</option><option>iOS</option></select></div><div><label>投放时段</label><select id="schedule"><option>全天</option><option>工作日 09:00–18:00</option><option>自定义时段</option></select></div></div>`:''}</div></div><div class="actions"><small>${editing?'保存后返回广告创意，已填写的创意内容不会丢失':'周期与预算默认继承计划'}</small><div class="save-actions">${editing?'<button class="secondary" onclick="cancelGroupEdit()">取消修改</button><button class="primary" onclick="saveGroupEdit()">保存并返回广告创意</button>':'<button class="secondary" onclick="groupOnly()">仅创建广告组</button><button class="primary" onclick="groupNext()">创建并添加创意</button>'}</div></div>`}
function creativeForm(){return `<div class="body"><div class="grid"><div><label>创意名称 *</label><input id="cname" value="${creative.name}" placeholder="选择素材后自动生成，可修改"></div><div><label>落地页链接 *</label><input id="landing" value="${creative.landing}" placeholder="https://"></div><div><label>广告素材 *</label><div class="upload" onclick="upload()">${uploaded?'<div><b style="color:#14825e">✓ summer-feed-1200x628.png</b><small>1200×628 · 规格校验通过</small></div>':'<div><b>上传素材或从素材库选择</b><small>仅展示符合当前广告形式的素材</small></div>'}</div></div><div><label>创意文案</label><input id="headline" value="${creative.headline}" placeholder="请输入标题"><div class="hint">字段根据广告形式动态展示</div></div></div></div><div class="actions"><small>提交后进入审核</small><button class="primary" onclick="submitCreative()">提交创意审核</button></div>`}
function toggleAdvanced(){captureGroup();advancedOpen=!advancedOpen;renderCreate(false)}
function done(){return `<div class="success">广告创建完成：计划和广告组已创建，广告创意正在审核中。</div>${strip()}<div class="card"><div class="summary"><div><small>广告创意</small><b>${creative.name}</b></div><div><small>状态</small><b>审核中</b></div><span></span><button class="primary" onclick="list()">返回广告投放列表</button></div></div>`}
function renderCreate(anchor=false){A.innerHTML=`<div class="top"><div><h1>创建 RTB 广告</h1><p>逐层创建，每一层创建成功后都可以结束或继续。</p></div><button class="outline" onclick="exit()">返回广告投放</button></div>${stage===3?done():`${strip()}<div id="editor" class="tree entering"><div class="node active"><article class="card"><div class="head"><div><h2>${['广告计划','广告组','广告创意'][stage]}</h2><p>${['定义整体投放周期与预算','在当前计划下配置一套投放策略','为当前广告组添加用户最终看到的内容'][stage]}</p></div><span></span><em class="badge">正在编辑</em></div>${stage===0?planForm():stage===1?groupForm():creativeForm()}</article></div></div>`}`;requestAnimationFrame(()=>document.querySelector('#editor')?.classList.remove('entering'))}
function render(){view==='list'?A.innerHTML=listHTML():renderCreate(false)}render();

/* V0.3 refinements: wide list, frozen actions, explicit 3-level expectation, persisted plan row. */
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="extra2.css?v=2026081311">');
let activePlanRow=null;
const originalStart=start;start=function(){activePlanRow=null;originalStart()};
function ensurePlanRow(){if(activePlanRow)return;activePlanRow=[plan.name,'C-NEW01','rtb',period==='long'?'长期投放':`${plan.start} 至 ${plan.end}`,'待添加广告组',period==='long'?`每日预算：$${plan.budget}`:`总预算：$${plan.budget}`,'—','—'];rows.unshift(activePlanRow)}
planOnly=function(){if(!keepPlan())return;ensurePlanRow();toast('广告计划已创建');setTimeout(list,450)};
planNext=function(){if(!keepPlan())return;ensurePlanRow();group.name=`${plan.name}｜组01`;transitionToStage(1)};
const originalKeepGroup=keepGroup;keepGroup=function(){const ok=originalKeepGroup();if(ok&&activePlanRow)activePlanRow[4]='待添加创意';return ok};
groupNext=function(){if(!keepGroup())return;creative.name=`${plan.name}｜创意01`;transitionToStage(2)};
upload=function(){creative.name=val('cname')||`${plan.name}｜创意01`;creative.landing=val('landing');creative.headline=val('headline');uploaded=true;renderCreate(false)};
const oldGroupForm=groupForm;groupForm=function(){return oldGroupForm().replace('placeholder="填写配置后可使用建议名称"','').replace('<button class="ghost" onclick="suggest()">使用建议名称</button>','').replace('</div><div><label>投放地区','<div class="hint">由广告计划名称自动衍生，可修改</div></div><div><label>投放地区')};
const oldListHTML=listHTML;listHTML=function(){return oldListHTML().replace('<th>预算 / 代投运营</th>','<th>预算</th><th>代投运营</th>').replaceAll(/<td>代投运营：([^<]+)<\/td>/g,'<td>—</td><td>$1</td>').replaceAll(/<td>((?:每日预算|总预算)：[^<]+)<\/td>/g,'<td>$1</td><td>—</td>')};
function flowSteps(){const progress=returnStage===null?stage:returnStage;const labels=[progress>0?plan.name:'广告计划',progress>1?group.name:'广告组',progress>2?creative.name:'广告创意'];return `<aside class="flow-steps" aria-label="创建层级"><div class="flow-title">创建层级</div>${labels.map((x,i)=>{const active=i===stage;const done=i<progress&&!active;const clickable=stage<3&&done&&(i===0||i===1&&progress===2);const unavailable=!active&&!clickable;const title=i===0?'返回修改广告计划':'返回修改广告组';return `<button class="flow-step ${done?'done':active?'on':''} ${clickable?'editable':''}" ${clickable?`onclick="editCompleted(${i})" title="${title}"`:unavailable?'disabled':''}><i>${done?'✓':i+1}</i><span><small>${done?(clickable?'已创建 · 可修改':'已创建'):active?'当前编辑':'稍后创建'}</small><b>${x}</b></span>${clickable?'<em>修改</em>':''}</button>`}).join('')}</aside>`}
const oldRenderCreate=renderCreate;renderCreate=function(anchor=false){oldRenderCreate(false);if(stage===1){['gname','geo','inv','fmt','bill','bid','device','os','schedule'].forEach(id=>{const el=document.querySelector('#'+id);if(el)el.value=group[id==='gname'?'name':id]||''})}document.querySelectorAll('input,select').forEach(el=>el.addEventListener('input',()=>el.classList.remove('invalid'),{once:true}));const top=A.querySelector('.top');if(!top)return;top.insertAdjacentHTML('afterend',flowSteps());const flow=A.querySelector('.flow-steps');const workspace=document.createElement('div');workspace.className='create-workspace';top.after(workspace);workspace.append(flow);while(workspace.nextSibling)workspace.append(workspace.nextSibling)};
strip=function(){return ''};
const oldRender=render;render=function(){A.classList.toggle('list-page',view==='list');A.classList.toggle('platform-page',!['list','create'].includes(view));oldRender()};render();

/* Complete platform navigation, adapted to the current visual and interaction framework. */
const pageMeta={dashboard:['仪表盘','投放总览与花费'],list:['广告投放','CPD 代投与 RTB 自助投放管理'],assets:['创意素材','素材文件夹与资源库'],reports:['数据报表','转化与花费分析'],billing:['充值账单','余额、充值与账户流水'],settings:['账户设置','资料、转化追踪与安全'],create:['创建 RTB 广告','按层创建计划、广告组与广告创意']};
let reportDays=7,settingsTab='profile',assetFolder='全部素材';
function setGlobalMeta(){const m=pageMeta[view]||pageMeta.list;document.querySelector('#globalTitle').textContent=m[0];document.querySelector('#globalSub').textContent=m[1];document.querySelectorAll('nav a[data-view]').forEach(a=>a.classList.toggle('on',a.dataset.view===(view==='create'?'list':view)))}
function go(next){if(view==='create'&&next!=='create'){exit();if(view==='create')return;view=next}else view=next;render()}
function dashboardHTML(){return `<div class="top"><div><h1>仪表盘</h1><p>近 7 天投放表现 · 数据更新于今天 08:30 UTC</p></div><button class="primary" onclick="openCreateChoice()">＋ 新建投放</button></div><div class="metric-grid">${[['总花费','$7,745.30','↑ 9.2%'],['展示量','6.68M','↑ 14.0%'],['点击量','48,400','↑ 6.4%'],['平均 CTR','0.72%','↑ 0.8%']].map(x=>`<div class="card metric"><small>${x[0]}</small><strong>${x[1]}</strong><em>${x[2]} 较上周</em></div>`).join('')}</div><div class="platform-grid"><div class="card"><div class="panel-head"><h3>每日花费趋势</h3><span></span><small>近 7 天</small></div><div class="panel-body"><div class="trend-chart">${[54,68,62,82,73,94,88].map((n,i)=>`<i style="height:${n}%" title="08-${7+i} · $${780+i*68}"></i>`).join('')}</div></div></div><div class="card"><div class="panel-head"><h3>投放类型花费</h3></div><div class="panel-body"><div class="donut"></div><div class="legend-row"><span><i style="background:#5b5bf0"></i>RTB</span><b>$3,717.74</b></div><div class="legend-row"><span><i style="background:#1f9d76"></i>CPD</span><b>$2,323.59</b></div><div class="legend-row"><span><i style="background:#e8a61a"></i>其他</span><b>$1,703.97</b></div></div></div></div><div class="card table-wrap"><div class="panel-head"><h3>计划表现</h3><span></span><button class="outline" onclick="go('list')">查看全部</button></div><table class="table"><thead><tr><th>广告计划</th><th>类型</th><th>状态</th><th>展示</th><th>点击</th><th>CTR</th><th>花费</th></tr></thead><tbody>${rows.slice(0,3).map((r,i)=>`<tr><td><b>${r[0]}</b><small>${r[1]}</small></td><td>${r[2].toUpperCase()}</td><td><span class="status">${r[4]}</span></td><td>${r[6]}</td><td>${r[7]}</td><td>${['0.68%','0.80%','0.58%'][i]}</td><td>${['$2,104.40','$1,386.20','$980.40'][i]}</td></tr>`).join('')}</tbody></table></div>`}
const assetData=[['summer-feed-1200x628.png','图片 · 1200×628','夏季推广'],['brand-video-15s.mp4','视频 · 1920×1080','品牌视频'],['game-reward-portrait.mp4','视频 · 1080×1920','游戏素材'],['finance-banner-728x90.png','图片 · 728×90','金融素材'],['shop-native-card.png','图片 · 1200×628','商城素材'],['logo-square.png','图片 · 512×512','品牌资产']];
function assetsHTML(){const data=assetFolder==='全部素材'?assetData:assetData.filter(x=>x[2]===assetFolder);return `<div class="top"><div><h1>创意素材</h1><p>统一管理可复用的图片与视频素材</p></div><button class="outline" onclick="openFolderModal()">＋ 新建文件夹</button><button class="primary" onclick="openUploadModal()">↑ 上传素材</button></div><div class="asset-shell"><div class="card"><div class="panel-head"><h3>文件夹</h3></div><div class="folder-list">${['全部素材','夏季推广','品牌视频','游戏素材','金融素材','商城素材','品牌资产'].map(x=>`<button class="${assetFolder===x?'on':''}" onclick="assetFolder='${x}';render()">▱ ${x}</button>`).join('')}</div></div><div class="card"><div class="panel-head"><h3>${assetFolder}</h3><span></span><select id="assetType"><option>全部类型</option><option>图片</option><option>视频</option></select><input placeholder="搜索素材名称"></div><div class="panel-body"><div class="asset-grid">${data.map((x,i)=>`<div class="asset-item"><div class="asset-thumb">${x[1].startsWith('视频')?'▶':'▧'}</div><div class="asset-info"><b>${x[0]}</b><small>${x[1]}</small><small>创建于 2026-08-${String(12-i).padStart(2,'0')}</small></div></div>`).join('')||'<div class="empty">该文件夹暂无素材</div>'}</div></div></div></div>`}
function reportsHTML(){const factor=reportDays===7?1:reportDays===14?1.92:4.18;return `<div class="top"><div><h1>数据报表</h1><p>按计划、类型与地区分析投放表现 · UTC</p></div><div class="report-controls">${[7,14,30].map(n=>`<button class="${reportDays===n?'on':''}" onclick="reportDays=${n};render()">近 ${n} 天</button>`).join('')}</div></div><div class="metric-grid">${[['总花费','$'+(7745.3*factor).toLocaleString(undefined,{maximumFractionDigits:2})],['总展示',(6.68*factor).toFixed(2)+'M'],['总点击',Math.round(48400*factor).toLocaleString()],['平均 CTR','0.72%']].map(x=>`<div class="card metric"><small>${x[0]}（近${reportDays}天）</small><strong>${x[1]}</strong></div>`).join('')}</div><div class="card" style="margin-bottom:18px"><div class="panel-head"><h3>每日花费</h3><span></span><small>近 ${reportDays} 天</small></div><div class="panel-body"><div class="trend-chart">${Array.from({length:Math.min(reportDays,14)},(_,i)=>`<i style="height:${50+(i*17)%46}%"></i>`).join('')}</div></div></div><div class="card table-wrap"><div class="panel-head"><h3>按计划明细</h3><span></span><select><option>按计划</option><option>按投放类型</option><option>按地区</option></select><button class="outline" onclick="toast('CSV 已开始下载')">导出 CSV</button></div><table class="table"><thead><tr><th>广告计划</th><th>类型</th><th>展示</th><th>点击</th><th>CTR</th><th>CPC</th><th>CPM</th><th>花费</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td><b>${r[0]}</b></td><td>${r[2].toUpperCase()}</td><td>${r[6]}</td><td>${r[7]}</td><td>${['0.68%','0.80%','0.58%','0.60%'][i]}</td><td>$0.${25+i*7}</td><td>$${(1.2+i*.2).toFixed(2)}</td><td>$${(2104-i*285).toLocaleString()}</td></tr>`).join('')}</tbody></table></div>`}
function billingHTML(){return `<div class="top"><div><h1>充值账单</h1><p>账户余额、充值与消费流水</p></div><button class="primary" onclick="openDepositModal()">＋ 账户充值</button></div><div class="metric-grid"><div class="card metric"><small>可用余额</small><strong>$8,420.50</strong><em>账户状态正常</em></div><div class="card metric"><small>本月充值</small><strong>$15,000.00</strong></div><div class="card metric"><small>本月消耗</small><strong>$12,486.30</strong></div><div class="card metric"><small>待确认金额</small><strong>$0.00</strong></div></div><div class="card table-wrap"><div class="panel-head"><h3>账户流水</h3><span></span><select><option>全部类型</option><option>充值</option><option>广告消耗</option><option>退款</option></select></div><table class="table"><thead><tr><th>时间</th><th>流水号</th><th>类型</th><th>说明</th><th>金额</th><th>状态</th></tr></thead><tbody>${[['2026-08-13 07:20','TX-26081301','充值','USDT 充值','+$5,000.00','已到账'],['2026-08-12 23:59','TX-26081288','广告消耗','当日 RTB 投放消耗','-$786.20','已完成'],['2026-08-11 23:59','TX-26081176','广告消耗','当日 CPD / RTB 消耗','-$824.50','已完成'],['2026-08-08 10:35','TX-26080812','充值','银行转账','+$10,000.00','已到账']].map(r=>`<tr>${r.map((c,i)=>`<td class="${i===4?'cell-main':''}">${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function settingsHTML(){const body=settingsTab==='profile'?`<div class="field-row"><div><label>公司名称</label><input value="T1 Advertiser Demo"></div><div><label>账户 ID</label><input value="70285" disabled></div></div><div class="field-row"><div><label>联系人</label><input value="Victor Wang"></div><div><label>联系邮箱</label><input value="victor@example.com"></div></div><div><label>账户时区</label><select><option>UTC</option><option>UTC+8 北京时间</option></select></div>`:settingsTab==='tracking'?`<div><label>转化追踪状态</label><p><span class="state-dot"></span>基础追踪代码已启用</p></div><div><label>全局 Pixel ID</label><input value="T1-PX-70285-A9F3"></div><div><label>回传地址</label><input value="https://track.example.com/postback"></div>`:`<div class="field-row"><div><label>登录密码</label><input type="password" value="123456789"></div><div><label>二步验证</label><select><option>尚未启用</option><option>启用</option></select></div></div><div><label>登录通知</label><select><option>新设备登录时通知</option><option>所有登录均通知</option></select></div>`;return `<div class="top"><div><h1>账户设置</h1><p>管理账户资料、转化追踪与安全设置</p></div></div><div class="card"><div class="settings-tabs">${[['profile','基础资料'],['tracking','转化追踪'],['security','账户安全']].map(x=>`<button class="${settingsTab===x[0]?'on':''}" onclick="settingsTab='${x[0]}';render()">${x[1]}</button>`).join('')}</div><div class="settings-form">${body}</div><div class="settings-actions"><button class="primary" onclick="toast('账户设置已保存')">保存修改</button></div></div>`}
function simpleModal(title,body,confirmText,confirmAction){document.body.insertAdjacentHTML('beforeend',`<div class="modal-mask" id="simpleMask" onclick="closeSimpleModal(event)"><div class="simple-modal" onclick="event.stopPropagation()"><div class="modal-head"><h3>${title}</h3></div><div class="modal-body">${body}</div><div class="modal-foot"><button class="outline" onclick="closeSimpleModal()">取消</button><button class="primary" onclick="${confirmAction}">${confirmText}</button></div></div></div>`)}
function closeSimpleModal(e){if(e&&e.target.id!=='simpleMask')return;document.querySelector('#simpleMask')?.remove()}
function openUploadModal(){simpleModal('上传素材','<label>上传至文件夹</label><select><option>当前文件夹</option><option>夏季推广</option><option>品牌资产</option></select><label>选择文件</label><div class="upload" onclick="toast(\'已选择 summer-banner.png\')"><b>点击选择图片或视频</b><small>支持 JPG / PNG / MP4，单文件不超过 50MB</small></div>','确认上传',"closeSimpleModal();toast('素材上传成功')")}
function openFolderModal(){simpleModal('新建文件夹','<label>文件夹名称</label><input placeholder="请输入文件夹名称"><label>所属目录</label><select><option>全部素材</option></select>','创建',"closeSimpleModal();toast('文件夹已创建')")}
function openDepositModal(){simpleModal('账户充值','<label>充值方式</label><select><option>USDT</option><option>银行转账</option></select><label>充值金额（USD）</label><input type="number" placeholder="请输入充值金额">','确认充值',"closeSimpleModal();toast('充值申请已提交')")}
const platformRender=render;render=function(){setGlobalMeta();A.classList.toggle('list-page',view==='list');A.classList.toggle('platform-page',!['list','create'].includes(view));if(view==='dashboard')A.innerHTML=dashboardHTML();else if(view==='assets')A.innerHTML=assetsHTML();else if(view==='reports')A.innerHTML=reportsHTML();else if(view==='billing')A.innerHTML=billingHTML();else if(view==='settings')A.innerHTML=settingsHTML();else platformRender();setGlobalMeta()};
const platformList=list;list=function(){view='list';render()};
const platformStart=start;start=function(){platformStart();setGlobalMeta()};
render();
