const A=document.querySelector('#app'),T=document.querySelector('#toast');let stage=0,period='long',uploaded=false;
const plan={name:'RTB计划｜20260813｜001',budget:'',start:'',end:''},group={name:'',geo:'',inv:'',fmt:'',bill:'',bid:''},creative={name:'',landing:''};
function toast(s){T.textContent=s;T.classList.add('show');setTimeout(()=>T.classList.remove('show'),1600)}
function val(id){return document.querySelector('#'+id)?.value.trim()||''}function savePlan(){plan.name=val('pname');plan.budget=val('budget');plan.start=val('start');plan.end=val('end');if(!plan.name||!plan.budget||!plan.start||(period==='fixed'&&!plan.end)){toast('请完成广告计划必填项');return}stage=1;render();toast('广告计划已创建')}
function saveGroup(){Object.assign(group,{name:val('gname'),geo:val('geo'),inv:val('inv'),fmt:val('fmt'),bill:val('bill'),bid:val('bid')});if(Object.values(group).some(v=>!v)){toast('请完成广告组必填项');return}stage=2;render();toast('广告组已创建')}
function saveCreative(){creative.name=val('cname');creative.landing=val('landing');if(!creative.name||!creative.landing||!uploaded){toast('请完成创意信息并选择素材');return}stage=3;render();toast('广告创意已提交审核')}
function leave(level){if(confirm(`${level}已创建，可以稍后从详情页继续添加下级内容。现在返回广告投放列表吗？`))toast('已返回列表（演示）')}
function resetFrom(n){if(confirm('修改已创建对象后，需要重新确认下级配置。继续吗？')){stage=n;render()}}
function setPeriod(p){period=p;render()}
function planEditor(){return `<div class="body"><div class="grid"><div><label>计划名称 <i class="req">*</i></label><input id="pname" value="${plan.name}"><div class="hint">按“投放类型｜创建日期｜当日序号”自动生成，可修改</div></div><div><label>投放周期 <i class="req">*</i></label><div class="seg"><button class="${period==='long'?'on':''}" onclick="setPeriod('long')">长期投放</button><button class="${period==='fixed'?'on':''}" onclick="setPeriod('fixed')">固定周期</button></div></div><div><label>${period==='long'?'每日预算':'活动总预算'}（USD）<i class="req">*</i></label><input id="budget" type="number" value="${plan.budget}" placeholder="请输入预算"></div><div><label>开始日期 <i class="req">*</i></label><input id="start" type="date" value="${plan.start}"></div>${period==='fixed'?`<div><label>结束日期 <i class="req">*</i></label><input id="end" type="date" value="${plan.end}"></div>`:''}</div></div><div class="actions"><small>创建后将生成正式计划，也可以暂不添加广告组</small><button class="primary" onclick="savePlan()">创建计划并继续</button></div>`}
function groupEditor(){return `<div class="body"><div class="grid"><div><label>广告组名称 <i class="req">*</i></label><input id="gname" value="${group.name}" placeholder="填写配置后可使用建议名称"></div><div><label>投放地区 <i class="req">*</i></label><select id="geo"><option value="">请选择</option><option>德国、法国</option><option>美国</option><option>全球</option></select></div><div><label>流量范围 <i class="req">*</i></label><select id="inv"><option value="">请选择</option><option>App</option><option>H5 移动网页</option><option>Web 桌面网页</option><option>App + H5</option></select></div><div><label>广告形式 <i class="req">*</i></label><select id="fmt"><option value="">请先选择流量范围</option><option>图片信息流</option><option>横幅广告</option><option>开屏图片</option></select></div><div><label>计费方式 <i class="req">*</i></label><select id="bill"><option value="">请选择</option><option>CPM · 按千次展示</option><option>CPC · 按点击</option></select></div><div><label>出价（USD）<i class="req">*</i></label><input id="bid" type="number" placeholder="请输入出价"><div class="hint">选择地区和计费方式后展示建议区间</div></div></div><div style="margin-top:14px"><button class="ghost" onclick="suggestName()">使用建议名称</button><button class="ghost">更多定向设置⌄</button></div></div><div class="actions"><small>周期与预算默认继承计划；需要时可在更多设置中调整</small><button class="ghost" onclick="leave('广告计划')">暂不添加</button><button class="primary" onclick="saveGroup()">创建广告组并继续</button></div>`}
function suggestName(){const g=val('geo')||'地区',i=val('inv')||'流量',f=val('fmt')||'广告形式';document.querySelector('#gname').value=`${g}｜${i}｜${f}｜01`}
function creativeEditor(){return `<div class="body"><div class="grid"><div><label>创意名称 <i class="req">*</i></label><input id="cname" value="${creative.name}" placeholder="选择素材后自动生成，可修改"></div><div><label>落地页链接 <i class="req">*</i></label><input id="landing" value="${creative.landing}" placeholder="https://"></div><div><label>广告素材 <i class="req">*</i></label><div class="upload" onclick="upload(this)">${uploaded?'<div><b style="color:#14825e">✓ summer-feed-1200x628.png</b><small>1200×628 · 规格校验通过</small></div>':'<div><b>上传素材或从素材库选择</b><small>系统仅展示符合“图片信息流”的素材</small></div>'}</div></div><div><label>创意文案</label><input placeholder="请输入标题"><div class="hint">文案字段根据广告形式动态展示</div></div></div></div><div class="actions"><small>提交后进入审核；审核通过前计划不会开始投放</small><button class="ghost" onclick="leave('广告组')">暂不添加</button><button class="primary" onclick="saveCreative()">提交创意审核</button></div>`}
function upload(){creative.name=val('cname')||'summer-feed-1200x628｜01';creative.landing=val('landing');uploaded=true;render()}
function node(n,title,sub,content,summary){const state=stage>n?'done':stage===n?'active':'disabled';return `<div class="node ${state}"><div class="dot">${stage>n?'✓':n+1}</div><article class="card"><div class="head"><div><h2>${title}</h2><p>${sub}</p></div><span></span><em class="badge ${stage>n?'ok':''}">${stage>n?'已创建':stage===n?'正在编辑':'等待上一级'}</em></div>${stage>n?summary:stage===n?content:''}</article></div>`}
function planSummary(){return `<div class="summary"><div><small>计划名称</small><b>${plan.name}</b></div><div><small>周期</small><b>${period==='long'?'长期投放':'固定周期'}</b></div><div><small>预算</small><b>$${plan.budget}${period==='long'?'/日':' 总预算'}</b></div><span></span><button class="ghost" onclick="resetFrom(0)">编辑计划</button>${stage===1?'<button class="outline" onclick="leave(\'广告计划\')">暂时结束</button>':''}</div>`}
function groupSummary(){return `<div class="summary"><div><small>广告组</small><b>${group.name}</b></div><div><small>定向与流量</small><b>${group.geo} · ${group.inv}</b></div><div><small>竞价</small><b>${group.bill.split('·')[0]} · $${group.bid}</b></div><span></span><button class="ghost" onclick="resetFrom(1)">编辑广告组</button>${stage===2?'<button class="outline" onclick="leave(\'广告组\')">暂时结束</button>':''}</div>`}
function creativeSummary(){return `<div class="summary"><div><small>广告创意</small><b>${creative.name}</b></div><div><small>审核状态</small><b style="color:#9a6a00">审核中</b></div><div><small>下一步</small><b>审核通过后自动投放</b></div><span></span><button class="outline" onclick="toast('进入计划详情（演示）')">查看计划详情</button></div>`}
function render(){A.innerHTML=`<div class="top"><div><h1>创建 RTB 广告</h1><p>逐层创建，每一层创建成功后都可以结束或继续。</p></div><button class="outline" onclick="leave('当前内容')">返回广告投放</button></div>${stage===3?'<div class="success">广告创建完成：计划和广告组已创建，广告创意正在审核中。</div>':''}<div class="tree">${node(0,'广告计划','定义整体投放周期与预算',planEditor(),planSummary())}${node(1,'广告组','在计划内配置一套投放策略',groupEditor(),groupSummary())}${node(2,'广告创意','为广告组添加用户最终看到的内容',creativeEditor(),creativeSummary())}</div>`}render();
