document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="extra.css">');
const A=document.querySelector('#app'),T=document.querySelector('#toast');let view='list',filter='all',stage=0,period='long',uploaded=false;
const d=new Date(),today=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,compact=today.replaceAll('-','');
const plan={name:`RTB计划｜${compact}｜001`,budget:'',start:today,end:''},group={name:'',geo:'',inv:'',fmt:'',bill:'',bid:''},creative={name:'',landing:''};
const rows=[['XX汽车｜新车上市｜App首页开屏｜0812-0818｜01','C-50271','cpd','2026-08-12 至 2026-08-18','投放中','代投运营：Amy','124万','8,420'],['优选商城｜欧洲再营销｜信息流｜长期｜01','C-50301','rtb','长期投放','投放中','每日预算：$120','68万','5,440'],['星游科技｜暑期拉新｜游戏中心激励视频｜0810-0824｜01','C-50288','cpd','2026-08-10 至 2026-08-24','投放中','代投运营：Ken','420万','24,500'],['未来金融｜巴西获客｜H5插屏｜长期｜01','C-50322','rtb','长期投放','待添加创意','每日预算：$100','—','—']];
function toast(s){T.textContent=s;T.classList.add('show');setTimeout(()=>T.classList.remove('show'),1600)}function val(id){return document.querySelector('#'+id)?.value.trim()||''}
function list(){view='list';render()}function start(){view='create';stage=0;period='long';uploaded=false;plan.name=`RTB计划｜${compact}｜001`;plan.budget='';plan.start=today;plan.end='';Object.keys(group).forEach(k=>group[k]='');Object.keys(creative).forEach(k=>creative[k]='');render()}
function listHTML(){let rs=rows.filter(r=>filter==='all'||r[2]===filter);return `<div class="top"><div><h1>广告投放</h1><p>统一查看 CPD 代投与 RTB 自助投放计划</p></div><button class="primary" onclick="start()">＋ 创建 RTB 广告</button></div><div class="toolbar"><div class="seg"><button class="${filter==='all'?'on':''}" onclick="filter='all';render()">全部投放</button><button class="${filter==='cpd'?'on':''}" onclick="filter='cpd';render()">CPD</button><button class="${filter==='rtb'?'on':''}" onclick="filter='rtb';render()">RTB</button></div><input placeholder="搜索计划名称 / ID"><span></span><small>CPD 由运营代投；RTB 由广告主自助管理</small></div><div class="card table-wrap"><table class="table"><thead><tr><th>广告计划</th><th>投放类型</th><th>投放周期</th><th>状态</th><th>预算 / 代投运营</th><th>展示</th><th>点击</th><th>操作</th></tr></thead><tbody>${rs.map(r=>`<tr><td><b>${r[0]}</b><small>${r[1]}</small></td><td><span class="type ${r[2]}">${r[2]==='cpd'?'CPD 代投':'RTB 自助投放'}</span></td><td>${r[3]}</td><td><span class="status ${r[4].includes('待')?'wait':''}">${r[4]}</span></td><td>${r[5]}</td><td>${r[6]}</td><td>${r[7]}</td><td class="row-actions"><button onclick="toast('查看计划详情（演示）')">查看</button>${r[2]==='rtb'?'<button onclick="toast(\'管理 RTB 计划（演示）\')">管理</button>':''}</td></tr>`).join('')}</tbody></table></div>`}
function exit(){if(stage===0&&!confirm('广告计划尚未创建，返回后当前填写内容不会保留。确定返回吗？'))return;list()}
function keepPlan(){plan.name=val('pname');plan.budget=val('budget');plan.start=val('start');plan.end=val('end');if(!plan.name||!plan.budget||!plan.start||(period==='fixed'&&!plan.end)){toast('请完成广告计划必填项');return false}if(+plan.budget<100){toast('预算不能低于 100 USD');return false}return true}
function planOnly(){if(!keepPlan())return;rows.unshift([plan.name,'C-NEW01','rtb',period==='long'?'长期投放':`${plan.start} 至 ${plan.end}`,'待添加广告组',period==='long'?`每日预算：$${plan.budget}`:`总预算：$${plan.budget}`,'—','—']);toast('广告计划已创建');setTimeout(list,450)}function planNext(){if(!keepPlan())return;stage=1;renderCreate(true)}
function keepGroup(){Object.assign(group,{name:val('gname'),geo:val('geo'),inv:val('inv'),fmt:val('fmt'),bill:val('bill'),bid:val('bid')});if(Object.values(group).some(v=>!v)){toast('请完成广告组必填项');return false}return true}function groupOnly(){if(!keepGroup())return;toast('广告组已创建');setTimeout(list,450)}function groupNext(){if(!keepGroup())return;stage=2;renderCreate(true)}
function submitCreative(){creative.name=val('cname');creative.landing=val('landing');if(!creative.name||!creative.landing||!uploaded){toast('请完成创意信息并选择素材');return}stage=3;renderCreate(true)}
function setPeriod(p){plan.name=val('pname')||plan.name;plan.budget=val('budget');plan.start=val('start')||today;plan.end=val('end');period=p;renderCreate(false)}function suggest(){document.querySelector('#gname').value=`${val('geo')||'地区'}｜${val('inv')||'流量'}｜${val('fmt')||'广告形式'}｜01`}function upload(){creative.name=val('cname')||'summer-feed-1200x628｜01';creative.landing=val('landing');uploaded=true;renderCreate(false)}
function strip(){let x=[];if(stage>0)x.push(`<div class="created-chip"><i>✓</i><div><small>广告计划</small><b>${plan.name}</b></div></div>`);if(stage>1)x.push(`<div class="created-chip"><i>✓</i><div><small>广告组</small><b>${group.name}</b></div></div>`);return x.length?`<div class="created-strip">${x.join(' › ')}</div>`:''}
function planForm(){return `<div class="body"><div class="grid"><div><label>计划名称 <i class="req">*</i></label><input id="pname" value="${plan.name}"><div class="hint">按“投放类型｜创建日期｜当日序号”生成，可修改</div></div><div><label>投放周期 <i class="req">*</i></label><div class="seg"><button class="${period==='long'?'on':''}" onclick="setPeriod('long')">长期投放</button><button class="${period==='fixed'?'on':''}" onclick="setPeriod('fixed')">固定周期</button></div></div><div><label>${period==='long'?'每日预算':'活动总预算'}（USD）<i class="req">*</i></label><input id="budget" type="number" min="100" value="${plan.budget}" placeholder="请输入，不低于 100 USD"><div class="hint">最低预算 100 USD</div></div><div><label>开始日期 <i class="req">*</i></label><input id="start" type="date" value="${plan.start}"><div class="hint">默认从今天开始，可调整</div></div>${period==='fixed'?`<div><label>结束日期 <i class="req">*</i></label><input id="end" type="date" value="${plan.end}"></div>`:''}</div></div><div class="actions"><small>创建后生成正式计划，不保存未提交表单</small><div class="save-actions"><button class="secondary" onclick="planOnly()">仅创建计划</button><button class="primary" onclick="planNext()">创建并添加广告组</button></div></div>`}
function groupForm(){return `<div class="body"><div class="grid"><div><label>广告组名称 *</label><input id="gname" value="${group.name}" placeholder="填写配置后可使用建议名称"></div><div><label>投放地区 *</label><select id="geo"><option value="">请选择</option><option>德国、法国</option><option>美国</option><option>全球</option></select></div><div><label>流量范围 *</label><select id="inv"><option value="">请选择</option><option>App</option><option>H5 移动网页</option><option>Web 桌面网页</option><option>App + H5</option></select></div><div><label>广告形式 *</label><select id="fmt"><option value="">请选择</option><option>图片信息流</option><option>横幅广告</option><option>开屏图片</option></select></div><div><label>计费方式 *</label><select id="bill"><option value="">请选择</option><option>CPM · 按千次展示</option><option>CPC · 按点击</option></select></div><div><label>出价（USD）*</label><input id="bid" type="number" placeholder="请输入出价"><div class="hint">选择地区和计费方式后展示建议区间</div></div></div><div style="margin-top:14px"><button class="ghost" onclick="suggest()">使用建议名称</button><button class="ghost">更多定向设置⌄</button></div></div><div class="actions"><small>周期与预算默认继承计划</small><div class="save-actions"><button class="secondary" onclick="groupOnly()">仅创建广告组</button><button class="primary" onclick="groupNext()">创建并添加创意</button></div></div>`}
function creativeForm(){return `<div class="body"><div class="grid"><div><label>创意名称 *</label><input id="cname" value="${creative.name}" placeholder="选择素材后自动生成，可修改"></div><div><label>落地页链接 *</label><input id="landing" value="${creative.landing}" placeholder="https://"></div><div><label>广告素材 *</label><div class="upload" onclick="upload()">${uploaded?'<div><b style="color:#14825e">✓ summer-feed-1200x628.png</b><small>1200×628 · 规格校验通过</small></div>':'<div><b>上传素材或从素材库选择</b><small>仅展示符合当前广告形式的素材</small></div>'}</div></div><div><label>创意文案</label><input placeholder="请输入标题"><div class="hint">字段根据广告形式动态展示</div></div></div></div><div class="actions"><small>提交后进入审核</small><button class="primary" onclick="submitCreative()">提交创意审核</button></div>`}
function done(){return `<div class="success">广告创建完成：计划和广告组已创建，广告创意正在审核中。</div>${strip()}<div class="card"><div class="summary"><div><small>广告创意</small><b>${creative.name}</b></div><div><small>状态</small><b>审核中</b></div><span></span><button class="primary" onclick="list()">返回广告投放列表</button></div></div>`}
function renderCreate(anchor=false){A.innerHTML=`<div class="top"><div><h1>创建 RTB 广告</h1><p>逐层创建，每一层创建成功后都可以结束或继续。</p></div><button class="outline" onclick="exit()">返回广告投放</button></div>${stage===3?done():`${strip()}<div id="editor" class="tree"><div class="node active"><div class="dot">${stage+1}</div><article class="card"><div class="head"><div><h2>${['广告计划','广告组','广告创意'][stage]}</h2><p>${['定义整体投放周期与预算','在当前计划下配置一套投放策略','为当前广告组添加用户最终看到的内容'][stage]}</p></div><span></span><em class="badge">正在编辑</em></div>${stage===0?planForm():stage===1?groupForm():creativeForm()}</article></div></div>`}`;if(anchor)requestAnimationFrame(()=>document.querySelector('#editor')?.scrollIntoView({behavior:'smooth',block:'start'}))}
function render(){view==='list'?A.innerHTML=listHTML():renderCreate(false)}render();
