/* Assertions come from independently exported Figma layer CSS, not this app's stylesheet. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/root/.openclaw/workspace/t1-dsp-benchmark-demo/node_modules/playwright');
const spec=require('../docs/t1-figma-style-reference.json'),base=process.env.DEMO_BASE||'http://127.0.0.1:8765';
const out=process.env.STYLE_OUTPUT||'/root/.openclaw/workspace/outputs/t1-figma-exact-20260929';
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true,args:['--no-sandbox']}),p=await b.newPage({viewport:{width:1440,height:900}});const errors=[],results=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/t1-p0-advertiser-platform/dsp.html?demo=1&review=1');await p.locator('#scopeAccountTrigger').waitFor();
let current='';for(const row of spec.checks){if(current!==row.route){if(current.startsWith('create')&&!row.route.startsWith('create'))await p.evaluate(()=>{App.ufWorking=null;App.editFlow=null;App.go('dash')});if(row.route==='login')await p.goto(base+'/t1-p0-advertiser-platform/login.html');else await p.evaluate(r=>{if(r==='create')App.startRtbCreate();else if(r==='create2')App.saveUfCampaign();else if(r==='create3'){App.saveUfGroup()}else if(r==='cpd')App.openGroupDetail('G-CPD-VERSION');else if(r==='notification'){App.go('dash');App.toggleNotif()}else App.go(r)},row.route);current=row.route;await p.waitForTimeout(700);}
const actual=await p.evaluate(({selector,expected})=>{const e=document.querySelector(selector);if(!e)return {missing:selector};const c=getComputedStyle(e);const got={},wanted={},problems=[];for(const[prop,value]of Object.entries(expected)){got[prop]=c.getPropertyValue(prop);if(prop==='font-family'){wanted[prop]=value.replaceAll("'",'');if(got[prop].split(',')[0].trim().replaceAll('"','')!==wanted[prop])problems.push(prop);continue}const el=document.createElement('span');el.style.setProperty(prop,value);el.style.position='absolute';document.body.append(el);wanted[prop]=getComputedStyle(el).getPropertyValue(prop);el.remove();if(got[prop]!==wanted[prop])problems.push(prop)}return {got,wanted,problems}},row);results.push({route:row.route,selector:row.selector,source:row.source,layer:row.layer,...actual});}
// Document fonts actually used. A matching family declaration does not prove the font file exists.
const fontAudit=[];for(const selector of ['#auth-login .auth-head h1','.auth-brand h2']){const session=await p.context().newCDPSession(p);await session.send('DOM.enable');await session.send('CSS.enable');const {root}=await session.send('DOM.getDocument');const {nodeId}=await session.send('DOM.querySelector',{nodeId:root.nodeId,selector});fontAudit.push({selector,...await session.send('CSS.getPlatformFontsForNode',{nodeId})});await session.detach()}
await p.screenshot({path:path.join(out,'login-verified.png')});await b.close();fs.writeFileSync(path.join(out,'style-parameter-verification.json'),JSON.stringify({base,source:spec.file,results,fontAudit,errors},null,2));const failed=results.filter(r=>r.missing||r.problems.length);console.log(JSON.stringify({checked:results.length,failed,errors},null,2));assert.equal(failed.length,0,'Figma parameter mismatches');assert.deepEqual(errors,[]);})();
