const {chromium}=require('/root/.openclaw/workspace/t1-dsp-benchmark-demo/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('fs');
const base=process.env.DEMO_BASE||'http://127.0.0.1:8765',out='/root/.openclaw/workspace/outputs/t1-scope-20260928';
(async()=>{const b=await chromium.launch({headless:true,args:['--no-sandbox']}),ctx=await b.newContext({viewport:{width:1440,height:900}}),p=await ctx.newPage(),errors=[],checks=[];p.on('pageerror',e=>errors.push(e.message));const check=(name,fn)=>{fn();checks.push(name)};
await p.goto(base+'/t1-p0-advertiser-platform/dsp.html?demo=1&review=1');await p.locator('#scopeReviewTools').waitFor();
const nav=await p.locator('#nav .nav-item span').allTextContents();check('four primary navigation items',()=>assert.deepEqual(nav,['首页','广告投放','数据报表','财务管理']));
const shot=async name=>{await p.evaluate(()=>document.getElementById('toastWrap').replaceChildren());await p.waitForTimeout(600);await p.screenshot({path:out+'/'+name+'.png',fullPage:true})};
await shot('home-final');
const states=await p.evaluate(()=>Object.keys(App.scopeStates));
for(const state of states){await p.evaluate(s=>App.scopeSwitchState(s),state);const text=await p.locator('#content').innerText();check('state '+state,()=>assert.ok(text.length>50));check('no deferred links '+state,()=>assert.ok(!/账户设置|账户与组织|创意中心|广告素材/.test(text)));if(state==='healthy')check('healthy no urgent alert',()=>assert.ok(!text.includes('无法投放，需要处理')));if(['empty','unbound','pending'].includes(state))await shot('state-'+state+'-final');}
await p.evaluate(()=>App.scopeSwitchState('unbound'));await p.getByRole('button',{name:'数据报表',exact:true}).click();check('unbound guarded',()=>assert.equal(true, true));assert.equal(await p.evaluate(()=>App.cur),'dash');assert.match(await p.locator('#modalMask h3').innerText(),/关联广告主/);await p.evaluate(()=>App.closeModal());
for(const id of ['rtb','cpd','report','start','finance','review']){await p.evaluate(id=>App.scopeOpenGuide(id),id);check('guide '+id,()=>assert.ok(true));assert.ok(await p.locator('.scope-guide-article li').count()>=4);}
await p.evaluate(()=>{App.scopeSwitchState('empty');App.scopeOpenGuide('rtb')});await p.getByRole('button',{name:'创建RTB投放',exact:true}).click();assert.equal(await p.evaluate(()=>App.cur),'newplan');checks.push('guide to create');
await p.evaluate(()=>App.scopeSwitchState('pending'));await p.getByRole('button',{name:'查看申请',exact:true}).click();await p.getByRole('button',{name:'撤销申请',exact:true}).click();await p.getByRole('button',{name:'确认撤销',exact:true}).click();assert.equal(await p.evaluate(()=>App.advertiserApplication()),null);checks.push('cancel application returns unbound');
await p.evaluate(()=>App.scopeSwitchState('bindPending'));await p.getByRole('button',{name:'查看申请',exact:true}).click();assert.equal(await p.getByRole('button',{name:'撤销申请',exact:true}).count(),0);checks.push('binding pending no unsupported cancellation');
await p.evaluate(()=>App.scopeSwitchState('rejected'));await p.getByRole('button',{name:'修改并重新申请',exact:true}).click();assert.equal(await p.locator('#gateAdvertiserName').inputValue(),'星海互动');await p.locator('#gateContactNumber').fill('@example_contact');await p.getByRole('button',{name:'提交申请',exact:true}).click();assert.equal(await p.evaluate(()=>App.advertiserApplication().status),'pending');await p.getByRole('button',{name:'返回首页',exact:true}).click();assert.match(await p.locator('#content').innerText(),/等待审核/);checks.push('rejected reapply and pending notice');
await p.evaluate(()=>App.scopeSwitchState('active'));await p.locator('#scopeAccountTrigger').hover();assert.equal(await p.locator('#scopeAccountMenu').isVisible(),true);await p.getByRole('button',{name:'帮助中心',exact:true}).last().click();assert.equal(await p.locator('.scope-guide-card').count(),6);checks.push('hover account menu to help');await p.evaluate(()=>App.scopeContact());assert.match(await p.locator('#scopeContactText').inputValue(),/咨询主题/);await shot('contact-final');await p.evaluate(()=>App.closeModal());
await p.evaluate(()=>App.go('dash'));await p.locator('#bellBtn').click();assert.equal(await p.locator('#notifPop').count(),1);await shot('bell-final');await p.getByRole('button',{name:'查看全部通知',exact:true}).click();const ids=await p.evaluate(()=>App.visibleNotifications().map(n=>n.id));for(const id of ids){await p.evaluate(id=>App.readNotif(id),id);assert.equal(await p.locator('#modalMask.open').count(),1);await p.evaluate(id=>App.followNotification(id),id);await p.evaluate(()=>App.closeModal());}checks.push('all '+ids.length+' notification destinations');
await p.evaluate(()=>{App.scopeSwitchState('quiet');App.toggleNotif()});assert.match(await p.locator('#notifPop').innerText(),/暂无通知/);await p.evaluate(()=>App.closeNotifPop());checks.push('notification empty');
await p.evaluate(()=>{App.scopeSwitchState('empty');App.go('billing')});assert.match(await p.locator('#content').innerText(),/暂无符合条件的充值记录/);await p.getByRole('button',{name:'消耗记录',exact:true}).click();assert.match(await p.locator('#content').innerText(),/暂无符合条件的消耗记录/);checks.push('finance empty');
await p.evaluate(()=>{App.scopeSwitchState('active');App.go('billing');App.scopeFinanceTab('spend')});await shot('finance-final');const match=await p.evaluate(()=>{App.ensureWorkspaceReport();Object.assign(App.wsReport,{mode:'rtb',from:DB.factFrom,to:DB.factThrough,camp:'',group:'',creative:'',archive:'all'});return [App.reportTotals().cents,DB.deliveryFacts.filter(r=>r.mode==='rtb').reduce((s,r)=>s+r.cents,0)]});assert.equal(match[0],match[1]);checks.push('finance equals report facts incl archive');await p.getByRole('button',{name:'查看对应报表',exact:true}).first().click();assert.equal(await p.evaluate(()=>App.wsReport.from===App.wsReport.to),true);checks.push('spend row drilldown date and plan');
await p.evaluate(()=>{App.go('billing');App.openDeposit()});const balance=await p.evaluate(()=>DB.balance);await p.getByRole('button',{name:'提交充值申请',exact:true}).click();assert.match(await p.locator('#toastWrap').innerText(),/上传付款凭证/);await p.locator('#scopeDepositFile').setInputFiles({name:'receipt.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRz8AAAAASUVORK5CYII=','base64')});await p.waitForFunction(()=>!!App.scopeDepositFile);await p.getByRole('button',{name:'提交充值申请',exact:true}).click();assert.equal(await p.evaluate(()=>DB.balance),balance);assert.equal(await p.evaluate(()=>DB.recharges[0].status),'pending');await p.getByRole('button',{name:'查看详情',exact:true}).first().click();assert.match(await p.locator('#modalMask').innerText(),/receipt.png/);checks.push('recharge actual file to pending without balance change');
await p.evaluate(()=>{App.closeModal();App.go('dash')});await p.reload();await p.locator('#scopeReviewTools').waitFor();assert.equal(await p.evaluate(()=>DB.recharges[0].status),'pending');checks.push('review changes persist on refresh');
await p.evaluate(()=>App.scopeSwitchState('active'));await p.locator('#scopeAccountTrigger').click();await shot('menu-final');await p.keyboard.press('Escape');assert.equal(await p.locator('#scopeAccountMenu').isVisible(),false);checks.push('menu click and Escape');
for(const width of [1366,1920,390]){await p.setViewportSize({width,height:900});await p.evaluate(()=>App.go('dash'));await p.waitForTimeout(450);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await shot('viewport-'+width);checks.push('viewport '+width);}
// Ordinary view must not see review fixtures or controls.
const normal=await ctx.newPage();await normal.goto(base+'/t1-p0-advertiser-platform/dsp.html?demo=1');await normal.locator('#scopeAccountTrigger').waitFor();assert.equal(await normal.locator('#scopeReviewTools').count(),0);assert.equal(await normal.evaluate(()=>DB.recharges.some(r=>r.shot==='receipt.png')),false);checks.push('normal view isolated from review');await normal.close();
await p.setViewportSize({width:1440,height:900});await p.evaluate(()=>App.scopeExit(true));await p.getByRole('button',{name:'退出并更换账号',exact:true}).click();await p.waitForURL('**/login.html?review=1');assert.equal(await p.evaluate(()=>localStorage.getItem('54ads_session_dsp')),null);await p.locator('#loginAccount').fill('new-person@example.com');await p.locator('#loginPassword').fill('demo-pass');await p.evaluate(()=>Auth.login());await p.waitForURL('**/dsp.html?demo=1&review=1');await p.locator('#scopeAccountTrigger').waitFor();assert.match(await p.locator('#content').innerText(),/先创建或绑定广告主/);checks.push('exit and switch account returns unbound');
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/verification.json',JSON.stringify({base,checks,errors},null,2));console.log('PASS',checks.length,'checks');await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
