const assert=require('node:assert/strict'),fs=require('node:fs');const {chromium}=require('/root/.openclaw/workspace/t1-dsp-benchmark-demo/node_modules/playwright');
const root=(process.env.DEMO_BASE||'http://127.0.0.1:8765')+'/t1-p0-advertiser-platform/versions/v2.1-design/',out='/root/.openclaw/workspace/outputs/t1-v21-design-20261006';
(async()=>{const b=await chromium.launch();const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[],checks=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await p.goto(root+'design.html');assert.equal(await p.locator('.tile').count(),31);await p.screenshot({path:out+'/design-index.png',fullPage:true});checks.push('31 directory links');await p.goto(root+'dsp.html?demo=1&review=1');const select=async id=>{await p.evaluate(id=>App.designSelect(id),id);await p.waitForTimeout(180)};
for(const c of await p.evaluate(()=>V21_DESIGN_CASES)){await select(c.id);assert.ok((await p.locator('#content').innerText()).length>20,c.id);assert.equal(await p.locator('#designCase').inputValue(),c.id);assert.equal(await p.locator('#content button:visible').filter({hasText:/^删除$/}).count(),0,c.id);if(['slots','upload','leave','review','versions','pause','archive'].includes(c.id))assert.ok(await p.locator('#modalMask').isVisible(),c.id+' modal');}checks.push('all 31 scene renders including modals, no delete buttons');
await select('new-creative');assert.ok(await p.locator('#uf-creative').isVisible());assert.deepEqual(await p.evaluate(()=>[DB.campaigns.length,DB.adGroups.length,DB.creatives.length]),await p.evaluate(()=>[App.designSeed.campaigns.length,App.designSeed.adGroups.length,App.designSeed.creatives.length]));await p.locator('#ufCreativeName').fill('设计验收创意');await p.locator('#ufLanding').fill('https://example.com/review');await p.evaluate(()=>App.saveUfCreative());assert.equal(await p.evaluate(()=>DB.creatives[0].name),'设计验收创意');assert.equal(await p.evaluate(()=>DB.creatives[0].status),'review');assert.equal(await p.evaluate(()=>DB.campaigns.length-App.designSeed.campaigns.length),1);checks.push('first two steps unsaved, final creates hierarchy once and submits review');
await select('slots');const slots=await p.evaluate(()=>JSON.stringify(App.v21Selection));await p.evaluate(()=>{App.v21SlotDraft=[];App.closeModal()});assert.equal(await p.evaluate(()=>JSON.stringify(App.v21Selection)),slots);checks.push('inventory cancel preserves original choice');
await select('rejected');assert.match(await p.locator('#content').innerText(),/落地页内容与素材不一致/);checks.push('rejection reason and edit refill');await select('versions');assert.match(await p.locator('#modalMask').innerText(),/待审新版标题/);await p.waitForTimeout(300);await p.screenshot({path:out+'/versions.png'});await p.evaluate(()=>{App.closeModal();App.openCreative('CR-3001')});assert.equal(await p.evaluate(()=>App.cur),'groupdetail');checks.push('two versions and pending edit guard');
await select('archive');await p.getByRole('button',{name:'确认归档',exact:true}).click();assert.equal(await p.evaluate(()=>DB.campaigns.find(c=>c.id==='C-1001').status),'archived');assert.equal(await p.evaluate(()=>DB.deliveryFacts.length),await p.evaluate(()=>App.designSeed.deliveryFacts.length));await select('archived');assert.ok(await p.getByRole('button',{name:'编辑广告计划',exact:true}).isDisabled());checks.push('archive retains historical facts and readonly details');
await select('report-cpd');assert.ok(!(await p.locator('#wrTable').innerText()).includes('CPC'));await select('report-empty');assert.match(await p.locator('#wrTable').innerText(),/没有投放记录/);await select('report-delay');assert.match(await p.locator('#wrWarning').innerText(),/数据尚未完整/);await select('report-error');await p.getByRole('button',{name:'重试',exact:true}).click();assert.ok(await p.locator('#wrKpis').isVisible());checks.push('CPD cost exclusion, no-record, delay and retry');
await select('report');const dl=p.waitForEvent('download');await p.getByRole('button',{name:'导出当前结果',exact:true}).click();const download=await dl;assert.match(download.suggestedFilename(),/\.csv$/);await download.saveAs(out+'/report-export-check.csv');await p.waitForTimeout(300);await p.screenshot({path:out+'/report.png'});checks.push('report actual download');
await select('new-creative');await p.waitForTimeout(300);await p.screenshot({path:out+'/create.png'});await p.setViewportSize({width:1366,height:768});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));checks.push('1366 desktop no page overflow');await p.goto(root+'dsp.html?demo=1&designcase=report');assert.equal(await p.locator('#designReview').count(),0);await p.evaluate(()=>App.go('members'));assert.equal(await p.evaluate(()=>App.cur),'report');checks.push('plain view no review selector and V2.2 routes unavailable');assert.deepEqual(errors,[]);fs.writeFileSync(out+'/verification.json',JSON.stringify({root,checks,errors},null,2));await b.close();console.log('PASS',checks.length,'groups + 31 scenes')})().catch(e=>{console.error(e);process.exit(1)})
