const applications=[
  {id:'AR-20260828-018',kind:'开户申请',applicant:'Alex Chen',company:'Nova Games Studio',product:'Nova Quest',contactApp:'Telegram',contact:'@alex_nova',email:'alex@example.com',time:'2026-08-28 08:04',status:'待商务初审',sales:'陈敏 / S-1042',industry:'游戏',site:'https://novagames.example',note:'计划在 T1 开展海外应用推广，希望创建新的广告主。'},
  {id:'AR-20260828-015',kind:'开户申请',applicant:'Mia Zhou',company:'Pine Mobile',product:'Pine Cleaner',contactApp:'WhatsApp',contact:'+65 8123 6678',email:'mia@pinemobile.example',time:'2026-08-28 07:38',status:'待组长复核',sales:'林晓 / S-1018',industry:'互联网服务',site:'https://pinemobile.example',note:'初审已完成：确认新客户，资料完整，无同名广告主。'},
  {id:'AR-20260827-109',kind:'开户申请',applicant:'Leo Wang',company:'Arcade Sprint',product:'Arcade Sprint',contactApp:'Telegram',contact:'@leo_arcade',email:'leo@arcadesprint.example',time:'2026-08-27 22:11',status:'待补充',sales:'陈敏 / S-1042',industry:'游戏',site:'—',note:'需要补充产品官网和原对接商务。'},
  {id:'BR-20260828-006',kind:'绑定申请',applicant:'Ivy Lin',company:'Blue Ocean Network',product:'Blue Mall',contactApp:'Telegram',contact:'@ivy_blueocean',email:'ivy@blueocean.example',time:'2026-08-28 08:21',status:'待商务初审',sales:'陈敏 / S-1042',industry:'电商零售',site:'https://blueocean.example',note:'历史客户，申请加入已有广告主。'},
  {id:'BR-20260827-082',kind:'绑定申请',applicant:'Ryan Xu',company:'Orchid Commerce',product:'Orchid Shop',contactApp:'WhatsApp',contact:'+86 138 0000 6721',email:'ryan@orchid.example',time:'2026-08-27 19:46',status:'待关键审批',sales:'王诚 / S-1007',industry:'电商零售',site:'https://orchid.example',note:'初审和组长复核均已通过，拟绑定 ADV-00019782。'},
  {id:'BR-20260826-043',kind:'绑定申请',applicant:'Nina Gao',company:'River Play',product:'River Run',contactApp:'Telegram',contact:'@nina_river',email:'nina@riverplay.example',time:'2026-08-26 14:23',status:'已通过',sales:'林晓 / S-1018',industry:'游戏',site:'https://riverplay.example',note:'已绑定 ADV-00018372。'}
];
const advertisers=[
  {id:'ADV-00023891',name:'Blue Ocean Network',sales:'陈敏',dept:'品牌业务部',status:'正常'},
  {id:'ADV-00019782',name:'Orchid Commerce',sales:'王诚',dept:'品牌业务部',status:'正常'},
  {id:'ADV-00018372',name:'River Play',sales:'林晓',dept:'海外商业部',status:'正常'},
  {id:'ADV-00017432',name:'Cosmo Labs',sales:'王诚',dept:'渠道业务部',status:'正常'}
];
const app=document.querySelector('#app');
const modalRoot=document.querySelector('#modalRoot');
let state={view:'advertisers',reviewType:'开户申请',reviewScope:'待处理',selected:null,selectedAdvertiser:null};
const pendingStatuses=['待商务初审','待组长复核','待关键审批'];
const statusClass=s=>({'待商务初审':'warning','待组长复核':'info','待关键审批':'info','待补充':'info','已通过':'success','已驳回':'danger','正常':'success'}[s]||'neutral');
const statusHtml=s=>`<span class="status ${statusClass(s)}">${s}</span>`;

function render(){
  app.innerHTML=state.view==='review'?reviewList():state.view==='detail'?reviewDetail(state.selected):advertiserList();
  bind();
}

function managementHeader(active){const count=k=>applications.filter(a=>a.kind===k&&pendingStatuses.includes(a.status)).length;return `<div class="page-head"><div class="page-title"><h1>广告主管理</h1><p>管理广告主档案，处理 T1 开户与绑定申请</p></div>${active==='广告主列表'?'<div class="head-actions"><button class="btn">⚙ 自定义列</button><button class="btn primary">＋ 创建广告主</button></div>':''}</div><div class="management-tabs"><button class="management-tab ${active==='广告主列表'?'active':''}" data-mgmt="广告主列表">广告主列表</button><button class="management-tab ${active==='开户申请'?'active':''}" data-mgmt="开户申请">开户申请 <span class="mini-count">${count('开户申请')}</span></button><button class="management-tab ${active==='绑定申请'?'active':''}" data-mgmt="绑定申请">绑定申请 <span class="mini-count">${count('绑定申请')}</span></button></div>`}

function reviewList(){
  const count=kind=>applications.filter(a=>a.kind===kind&&pendingStatuses.includes(a.status)).length;
  const rows=applications.filter(a=>a.kind===state.reviewType&&(state.reviewScope==='全部申请'||pendingStatuses.includes(a.status)));
  return `${managementHeader(state.reviewType)}
  <section class="card filter-card"><div class="filters" style="grid-template-columns:1.3fr .8fr .8fr auto"><div class="field"><label>申请人 / 广告主</label><input class="input" placeholder="姓名、公司名称或申请 ID"></div><div class="field"><label>提交时间</label><select class="select"><option>近 30 天</option><option>近 7 天</option></select></div><div class="field"><label>归属销售</label><select class="select"><option>全部</option><option>陈敏</option><option>林晓</option></select></div><div class="filter-actions"><button class="btn primary">查询</button><button class="btn">重置</button></div></div></section>
  <section class="card list-card"><div class="review-subtabs"><button class="review-subtab ${state.reviewScope==='待处理'?'active':''}" data-scope="待处理">待处理 <span class="mini-count">${count(state.reviewType)}</span></button><button class="review-subtab ${state.reviewScope==='全部申请'?'active':''}" data-scope="全部申请">全部申请</button></div><div class="table-wrap"><table><thead><tr><th>申请 ID</th><th>申请人</th><th>产品应用 / 广告主</th><th>联系方式</th><th>对接商务</th><th>提交时间</th><th>审核阶段</th><th>操作</th></tr></thead><tbody>${rows.map(a=>`<tr><td class="id-text">${a.id}</td><td>${a.applicant}</td><td><strong>${a.product}</strong></td><td>${a.contactApp} · ${a.contact}</td><td>${a.sales}</td><td>${a.time}</td><td>${statusHtml(a.status)}</td><td><button class="btn link" data-app="${a.id}">${pendingStatuses.includes(a.status)?'处理':'查看'}</button></td></tr>`).join('')}</tbody></table></div><div class="pagination"><span>共 ${rows.length} 条</span><button class="page-btn">‹</button><button class="page-btn active">1</button><button class="page-btn">›</button></div></section>`;
}

function reviewDetail(a){
  const opening=a.kind==='开户申请';
  const stage=a.status==='待商务初审'?1:a.status==='待组长复核'?2:a.status==='待关键审批'?3:3;
  const target=advertisers.find(x=>x.name===a.company)||advertisers[0];
  const primary=stage===1?'提交组长复核':stage===2?'复核通过并提交关键审批':opening?'终审通过并创建广告主':'终审通过并确认绑定';
  const stagePanel=stage===1?(opening?`<div class="field" style="margin-bottom:12px"><label>所属部门</label><select class="select"><option>海外商业部</option><option>品牌业务部</option></select></div><div class="field" style="margin-bottom:16px"><label>归属销售</label><select class="select"><option>${a.sales}</option><option>陈敏 / S-1042</option><option>林晓 / S-1018</option></select></div>`:searchPicker()):`<div class="review-conclusion"><span>商务初审结论</span><strong>${opening?'确认新客户，建议创建 SSP 广告主':'身份核验通过，拟绑定以下广告主'}</strong></div>${!opening?selectedAdvertiserHtml(target):''}${stage===3?'<div class="review-conclusion" style="margin-top:12px"><span>商务组长复核结论</span><strong>复核通过，同意提交关键审批</strong></div>':''}`;
  return `<button class="back-link" data-action="back">← 返回${a.kind}</button><div class="page-head"><div class="page-title"><h1>处理${a.kind}</h1><p>${a.id} · 提交于 ${a.time}</p></div></div>${auditFlow(stage)}<div class="review-detail"><div class="card tab-content"><div class="section"><div class="section-title">T1 提交信息</div><div class="info-grid">
    ${copyInfo(opening?'创建人':'绑定人',a.applicant)}${copyInfo(`${opening?'创建人':'绑定人'}联系方式`,`${a.contactApp} · ${a.contact}`)}${copyInfo(`${opening?'创建人':'绑定人'}邮箱地址`,a.email)}
    ${copyInfo('广告主名称',a.company)}${copyInfo('产品应用名',a.product)}${copyInfo('产品或官网链接',a.site)}
    ${copyInfo('所属行业',a.industry,false)}${copyInfo('对接商务',a.sales)}<div class="info-item"><span>申请类型</span><strong>${a.kind}</strong></div>
  </div></div><div class="section"><div class="section-title">申请说明</div><div class="result-note">${a.note}</div></div><div class="section"><div class="section-title">审核规则</div><div class="warning-box">所有开户及绑定申请必须依次通过商务初审、商务组长复核和关键审批。终审通过前不会创建或绑定广告主。</div></div></div><aside class="card review-side decision-card"><h3>${stage===1?'商务初审':stage===2?'商务组长复核':'关键审批'}</h3><p>${stage===1?(opening?'回访核验后提交组长复核。':'核验身份、选择广告主后提交组长复核。'):stage===2?'复核初审资料和处理结论。':'核对前两级结论并完成终审。'}</p>${stagePanel}<div class="decision-actions"><button class="btn primary" data-decision="approve" ${stage===1&&!opening&&!state.selectedAdvertiser?'disabled':''}>${primary}</button><button class="btn" data-decision="supplement">退回补充资料</button><button class="btn" data-decision="reject">驳回申请</button></div></aside></div>`;
}

function auditFlow(stage){return `<div class="audit-flow">${[1,2,3].map((n,i)=>`<div class="audit-step ${n<stage?'done':n===stage?'active':''}"><b>${n<stage?'✓':n}</b><span>${['商务初审','组长复核','关键审批'][i]}</span></div>`).join('')}</div>`}

function copyInfo(label,value,copy=true){return `<div class="info-item"><span>${label}</span><div class="copy-line"><strong>${value||'—'}</strong>${copy&&value&&value!=='—'?`<button class="copy-btn" data-copy="${escapeAttr(value)}" aria-label="复制${label}" title="复制">⧉</button>`:''}</div></div>`}
function escapeAttr(v){return String(v).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;')}
function searchPicker(){return `<div class="field" style="margin-bottom:16px"><label>选择 SSP 广告主</label><div class="search-picker"><input id="advertiserSearch" class="input" autocomplete="off" placeholder="搜索名称、Advertiser ID 或归属销售"><div id="searchResults" class="search-results" hidden></div></div><div id="selectedAdvertiser">${state.selectedAdvertiser?selectedAdvertiserHtml(state.selectedAdvertiser):''}</div><p class="helper">请核对名称、ID、部门及归属销售后再确认绑定。</p></div>`}
function selectedAdvertiserHtml(a){return `<div class="selected-advertiser"><strong>${a.name}</strong><span>${a.id} · ${a.dept} · ${a.sales}</span></div>`}

function advertiserList(){
  return `${managementHeader('广告主列表')}<section class="card filter-card"><div class="filters" style="grid-template-columns:1.5fr 1fr 1fr auto"><div class="field"><label>广告主</label><input class="input" placeholder="名称或 Advertiser ID"></div><div class="field"><label>归属销售</label><select class="select"><option>全部</option></select></div><div class="field"><label>状态</label><select class="select"><option>全部</option><option>正常</option></select></div><div class="filter-actions"><button class="btn primary">查询</button><button class="btn">重置</button></div></div></section><section class="card list-card"><div class="list-toolbar"><strong>广告主列表</strong><span class="count">共 ${advertisers.length} 条</span></div><div class="table-wrap"><table><thead><tr><th>广告主名称</th><th>SSP Advertiser ID</th><th>所属部门</th><th>归属销售</th><th>状态</th><th>操作</th></tr></thead><tbody>${advertisers.map(a=>`<tr><td><button class="name-link">${a.name}</button></td><td class="id-text">${a.id}</td><td>${a.dept}</td><td>${a.sales}</td><td>${statusHtml(a.status)}</td><td><div class="row-actions"><button>编辑</button><button class="more" data-more="${a.id}">更多⌄</button></div></td></tr>`).join('')}</tbody></table></div></section>`;
}

function bind(){
  document.querySelectorAll('[data-nav]').forEach(el=>el.addEventListener('click',()=>{state.view='advertisers';render()}));
  document.querySelectorAll('[data-mgmt]').forEach(el=>el.addEventListener('click',()=>{if(el.dataset.mgmt==='广告主列表'){state.view='advertisers'}else{state.reviewType=el.dataset.mgmt;state.reviewScope='待处理';state.view='review'}render()}));
  document.querySelectorAll('[data-type]').forEach(el=>el.addEventListener('click',()=>{state.reviewType=el.dataset.type;state.reviewScope='待处理';render()}));
  document.querySelectorAll('[data-scope]').forEach(el=>el.addEventListener('click',()=>{state.reviewScope=el.dataset.scope;render()}));
  document.querySelectorAll('[data-app]').forEach(el=>el.addEventListener('click',()=>{state.selected=applications.find(a=>a.id===el.dataset.app);state.selectedAdvertiser=null;state.view='detail';render();scrollTo(0,0)}));
  document.querySelector('[data-action="back"]')?.addEventListener('click',()=>{state.view='review';render()});
  document.querySelectorAll('[data-decision]').forEach(el=>el.addEventListener('click',()=>decisionModal(el.dataset.decision,state.selected)));
  document.querySelectorAll('[data-copy]').forEach(el=>el.addEventListener('click',()=>copyText(el.dataset.copy)));
  document.querySelectorAll('[data-more]').forEach(el=>el.addEventListener('click',e=>showMore(e.currentTarget,advertisers.find(a=>a.id===e.currentTarget.dataset.more))));
  const search=document.querySelector('#advertiserSearch');if(search){search.addEventListener('focus',()=>showSearch(search.value));search.addEventListener('input',()=>showSearch(search.value));document.addEventListener('click',e=>{if(!e.target.closest('.search-picker'))document.querySelector('#searchResults')?.setAttribute('hidden','')},{once:true})}
}
function showSearch(query){const box=document.querySelector('#searchResults');const q=query.trim().toLowerCase();const hits=advertisers.filter(a=>!q||`${a.name}${a.id}${a.sales}${a.dept}`.toLowerCase().includes(q));box.innerHTML=hits.length?hits.map(a=>`<button class="search-option" data-pick="${a.id}"><strong>${a.name}</strong><span>${a.id} · ${a.dept} · ${a.sales}</span></button>`).join(''):'<div class="helper" style="padding:12px">未找到匹配广告主</div>';box.hidden=false;box.querySelectorAll('[data-pick]').forEach(el=>el.onclick=()=>{state.selectedAdvertiser=advertisers.find(a=>a.id===el.dataset.pick);box.hidden=true;document.querySelector('#selectedAdvertiser').innerHTML=selectedAdvertiserHtml(state.selectedAdvertiser);document.querySelector('[data-decision="approve"]').disabled=false})}
async function copyText(text){try{await navigator.clipboard.writeText(text)}catch{const t=document.createElement('textarea');t.value=text;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove()}toast('已复制：'+text)}
function syncNav(){document.querySelectorAll('[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav==='advertisers'))}
function showMore(anchor,a){document.querySelector('.action-popover')?.remove();const r=anchor.getBoundingClientRect();const menu=document.createElement('div');menu.className='action-popover';menu.style.left=`${Math.min(innerWidth-184,r.right-172)}px`;menu.style.top=`${Math.min(innerHeight-90,r.bottom+6)}px`;menu.innerHTML='<button data-menu="ads">查看广告</button><button data-menu="invite">生成 T1 邀请</button>';document.body.appendChild(menu);menu.querySelector('[data-menu="ads"]').onclick=()=>{menu.remove();toast('已进入广告管理，并带入当前广告主筛选条件')};menu.querySelector('[data-menu="invite"]').onclick=()=>{menu.remove();inviteModal(a)};setTimeout(()=>document.addEventListener('click',e=>{if(!e.target.closest('.action-popover')&&e.target!==anchor)menu.remove()},{once:true}),0)}
function inviteModal(a){modalRoot.innerHTML=`<div class="modal-mask"><div class="modal" style="max-width:520px"><div class="modal-head"><h3>生成 T1 邀请</h3><button class="modal-close">×</button></div><div class="modal-body"><div class="invite-summary"><strong>${a.name}</strong><span>${a.id} · ${a.dept} · ${a.sales}</span></div><div class="form-grid"><div class="field"><label>成功使用次数</label><input class="input" value="1" disabled><p class="helper">一期仅支持单次成功使用</p></div><div class="field"><label>有效期</label><select class="select"><option>7 天</option><option>3 天</option><option>24 小时</option></select></div><div class="field full"><label>邀请备注</label><textarea class="textarea" placeholder="选填，例如客户名称或对接事项"></textarea></div></div><div class="warning-box">邀请将绑定当前明确的 SSP Advertiser ID。客户确认后直接加入该广告主，不再进入开户或绑定审核。</div></div><div class="modal-foot"><button class="btn modal-cancel">取消</button><button class="btn primary modal-submit">生成邀请</button></div></div></div>`;wireModal(()=>inviteResult(a))}
function inviteResult(a){const code='T1-'+a.id.slice(-5)+'-8K4P',link=`https://t1.example.com/register?invite=${code}`;modalRoot.innerHTML=`<div class="modal-mask"><div class="modal" style="max-width:520px"><div class="modal-head"><h3>邀请已生成</h3><button class="modal-close">×</button></div><div class="modal-body"><div class="invite-result"><div class="invite-result-icon">✓</div><h4>可以发送给客户了</h4><p>邀请码与注册链接对应同一次邀请，任一方式成功绑定后即失效。</p></div><div class="field"><label>邀请码</label><div class="copy-value"><code>${code}</code><button class="copy-btn" data-result-copy="${code}">⧉ 复制</button></div></div><div class="field" style="margin-top:14px"><label>带邀请码的注册链接</label><div class="copy-value"><code>${link}</code><button class="copy-btn" data-result-copy="${link}">⧉ 复制</button></div></div><div class="info-grid" style="margin-top:18px"><div class="info-item"><span>目标广告主</span><strong>${a.name}</strong></div><div class="info-item"><span>剩余使用次数</span><strong>1 次</strong></div><div class="info-item"><span>有效期</span><strong>7 天</strong></div></div><div class="inline-actions"><button class="btn" data-revoke>撤销邀请</button></div></div><div class="modal-foot"><button class="btn primary modal-close-result">完成</button></div></div></div>`;document.querySelectorAll('[data-result-copy]').forEach(el=>el.onclick=()=>copyText(el.dataset.resultCopy));document.querySelector('[data-revoke]').onclick=()=>{closeModal();toast('邀请已撤销，邀请码和注册链接均已失效')};document.querySelector('.modal-close').onclick=closeModal;document.querySelector('.modal-close-result').onclick=closeModal}
function wireModal(submit){document.querySelector('.modal-close')?.addEventListener('click',closeModal);document.querySelector('.modal-cancel')?.addEventListener('click',closeModal);document.querySelector('.modal-submit')?.addEventListener('click',submit);document.querySelector('.modal-mask')?.addEventListener('click',e=>{if(e.target.classList.contains('modal-mask'))closeModal()})}
function decisionModal(decision,a){
  const stage=a.status==='待商务初审'?1:a.status==='待组长复核'?2:3;
  const approve=stage===1?{title:'提交商务组长复核',desc:'本次操作不会创建或绑定广告主。申请将进入第二级审核，由商务组长复核。',submit:'确认提交复核'}:stage===2?{title:'提交关键审批',desc:'本次操作不会创建或绑定广告主。申请将进入第三级关键审批。',submit:'确认提交关键审批'}:a.kind==='开户申请'?{title:'终审通过并创建广告主',desc:'三级审核全部通过后，系统将创建 SSP 广告主、绑定 T1 用户并回传结果。',submit:'终审通过并创建'}:{title:'终审通过并确认绑定',desc:'三级审核全部通过后，系统将把 T1 用户绑定至已确认的 SSP 广告主。',submit:'终审通过并绑定'};
  const data={approve,supplement:{title:'要求补充资料',desc:'请说明需要客户补充的内容，T1 将通知申请人。',submit:'发送补充要求'},reject:{title:'驳回申请',desc:'申请结束后不会创建或绑定广告主，请填写明确原因。',submit:'确认驳回'}}[decision];
  modalRoot.innerHTML=`<div class="modal-mask"><div class="modal" style="max-width:480px"><div class="modal-head"><h3>${data.title}</h3><button class="modal-close">×</button></div><div class="modal-body"><div class="${decision==='reject'?'warning-box':'result-note'}">${data.desc}</div>${decision!=='approve'?'<div class="field"><label>说明 *</label><textarea class="textarea" placeholder="请输入具体说明"></textarea></div>':''}</div><div class="modal-foot"><button class="btn modal-cancel">取消</button><button class="btn ${decision==='reject'?'danger':'primary'} modal-submit">${data.submit}</button></div></div></div>`;
  document.querySelector('.modal-close').onclick=closeModal;document.querySelector('.modal-cancel').onclick=closeModal;document.querySelector('.modal-submit').onclick=()=>{closeModal();toast('处理结果已提交，系统将自动同步至 T1');state.view='review';render()};document.querySelector('.modal-mask').onclick=e=>{if(e.target.classList.contains('modal-mask'))closeModal()};
}
function closeModal(){modalRoot.innerHTML=''}
function toast(text){document.querySelector('#toastRoot').innerHTML=`<div class="toast">${text}</div>`;setTimeout(()=>document.querySelector('#toastRoot').innerHTML='',2200)}
render();
